NAME = template
DATASET = 0
TYPE = vector # vector, matrix, or image

include ../CS483.mk

EXP = data/$(DATASET)/output.raw
IN = data/$(DATASET)/col.raw,data/$(DATASET)/row.raw,data/$(DATASET)/data.raw,data/$(DATASET)/vec.raw
